# Generated by Django 2.2.19 on 2022-10-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20221001_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsrecipes',
            name='amount',
            field=models.FloatField(verbose_name='Количество'),
        ),
    ]
