# Generated by Django 2.2.19 on 2022-10-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20221001_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsrecipes',
            name='amount',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
